CREATE TYPE roles AS ENUM ('it', 'nurse');

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(26) NOT NULL PRIMARY KEY,
  nip BIGINT NOT NULL,
  name VARCHAR(50) NOT NULL,
  password VARCHAR(60) NULL,
  role roles NOT NULL,
  card_image_url TEXT NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);